apiVersion: apps/v1
kind: Deployment
metadata:
  name: nibe-gateway
  namespace: infra
  labels:
    k8s-app: nibe-gateway
  annotations:
    gitlab: "https://gitlab.com/garokube/nibe-gateway"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      k8s-app: nibe-gateway
  template:
    metadata:
      labels:
        k8s-app: nibe-gateway
    spec:
      imagePullSecrets:
        - name: nibe-gateway-deploy-key
      containers:
        - name: main
          image: registry.gitlab.com/garokube/nibe-gateway:__VERSION__ 
          resources:
            limits:
              memory: 256Mi
            requests:
              memory: 80Mi
              cpu: "0.1"
          env:
            - name: GATEWAY_ADDRESS
              value: "172.16.142.10"
            - name: DEBUG_LEVEL
              value: "DEBUG"
            - name: ENABLE_READ_COMMANDS
              value: "true"
          ports:
            - name: http
              containerPort: 3000
            - name: nibe
              containerPort: 9999
              protocol: UDP

---
apiVersion: v1
kind: Service
metadata:
  name: nibe-gateway 
  namespace: infra
  labels:
    k8s-app: nibe-gateway
  annotations:
    gitlab: "https://gitlab.com/garokube/nibe-gateway"
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: nibe
      protocol: UDP
      port: 9999
      targetPort: 9999
  selector:
    k8s-app: nibe-gateway
  type: ClusterIP

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nibe-gateway
  namespace: infra
  labels:
    release: mon
spec:
  selector:
    matchLabels:
      k8s-app: nibe-gateway
  endpoints:
  - port: http
    interval: 30s
    path: /metrics

